#!/bin/bash
#check if the system is 32/64 bits

if [ $(getconf LONG_BIT) -eq 32 ]; then
	max_pid=$((2**15 - 1))
	echo "This is a 32 bit system"
else
	max_pid=$((2**31 - 1))
	echo "This is NOT A 32 BIT system"
fi

echo "Max PID on this computer is: $max_pid"
